module.exports = {
    product: {
    	"Alto k10": "https://www.marutisuzuki.com/channels/arena/hatchbacks/alto-k10",
		"WagonR": "https://www.marutisuzuki.com/channels/arena/hatchbacks/wagonr",
		"Celerio": "https://www.marutisuzuki.com/channels/arena/hatchbacks/celerio",
		"CelerioX": "https://www.marutisuzuki.com/channels/arena/hatchbacks/celerio-x",
		"New Swift": "https://www.marutisuzuki.com/channels/arena/hatchbacks/swift",
		"Alto 800": "https://www.marutisuzuki.com/channels/arena/hatchbacks/alto-800",
		"Dzire": "https://www.marutisuzuki.com/channels/arena/sedans/dzire",
		"Vitarra Brezza": "https://www.marutisuzuki.com/channels/arena/suvs-muvs/vitara-brezza",
		"Ertiga": "https://www.marutisuzuki.com/channels/arena/suvs-muvs/ertiga",
		"EECO": "https://www.marutisuzuki.com/channels/arena/vans/eeco",
		"SCROSS": "https://www.nexaexperience.com/s-cross.html",
		"CIAZ S": "https://www.nexaexperience.com/ciaz-s.html",
		"CIAZ": "https://www.nexaexperience.com/ciaz.html",
		"Baleno": "https://www.nexaexperience.com/baleno.html",
		"Ignis": "https://www.nexaexperience.com/ignis.html",
		"Baleno RS": "https://www.nexaexperience.com/baleno-rs.html",
		"OMNI": "https://www.marutisuzuki.com/corporate/reach-us/contact-us",
		"Gypsy": "https://www.marutisuzuki.com/corporate/reach-us/contact-us"
    },

    testDrive: {
    	"Alto k10": "https://www.marutisuzuki.com/channels/arena/hatchbacks/alto-k10",
		"WagonR": "https://www.marutisuzuki.com/channels/arena/hatchbacks/wagonr",
		"Celerio": "https://www.marutisuzuki.com/channels/arena/hatchbacks/celerio",
		"CelerioX": "https://www.marutisuzuki.com/channels/arena/hatchbacks/celerio-x",
		"New Swift": "https://www.marutisuzuki.com/channels/arena/hatchbacks/swift",
		"Alto 800": "https://www.marutisuzuki.com/channels/arena/hatchbacks/alto-800",
		"Dzire": "https://www.marutisuzuki.com/channels/arena/sedans/dzire",
		"Vitarra Brezza": "https://www.marutisuzuki.com/channels/arena/suvs-muvs/vitara-brezza",
		"Ertiga": "https://www.marutisuzuki.com/channels/arena/suvs-muvs/ertiga",
		"EECO": "https://www.marutisuzuki.com/channels/arena/vans/eeco",
		"SCROSS": "https://www.nexaexperience.com/book-test-drive.html",
		"CIAZ S": "https://www.nexaexperience.com/book-test-drive.html",
		"CIAZ": "https://www.nexaexperience.com/book-test-drive.html",
		"Baleno": "https://www.nexaexperience.com/book-test-drive.html",
		"Ignis": "https://www.nexaexperience.com/book-test-drive.html",
		"Baleno RS": "https://www.nexaexperience.com/book-test-drive.html",
		"OMNI": "https://www.marutisuzuki.com/corporate/reach-us/contact-us",
		"Gypsy": "https://www.marutisuzuki.com/corporate/reach-us/contact-us"	
    },

    ebook: {
    	"Alto k10": "https://www.marutisuzuki.com/channels/arena/service/ebook-car?model=AK",
		"WagonR": "https://www.marutisuzuki.com/channels/arena/service/ebook-car?model=WM",
		"Celerio": "https://www.marutisuzuki.com/channels/arena/service/ebook-car?model=CE",
		"CelerioX": "https://www.marutisuzuki.com/channels/arena/service/ebook-car?model=CX",
		"New Swift": "https://www.marutisuzuki.com/channels/arena/service/ebook-car?model=SR",
		"Alto 800": "https://www.marutisuzuki.com/channels/arena/service/ebook-car?model=AN",
		"Dzire": "https://www.marutisuzuki.com/channels/arena/service/ebook-car?model=DR",
		"Vitarra Brezza": "https://www.marutisuzuki.com/channels/arena/service/ebook-car?model=VB",
		"Ertiga": "https://www.marutisuzuki.com/channels/arena/service/ebook-car?model=R3",
		"EECO": "https://www.marutisuzuki.com/channels/arena/service/ebook-car?model=VR",
		"SCROSS": "https://www.nexaexperience.com/login.html?url=/buy-now.aspx",
		"CIAZ S": "https://www.nexaexperience.com/login.html?url=/buy-now.aspx",
		"CIAZ": "https://www.nexaexperience.com/login.html?url=/buy-now.aspx",
		"Baleno": "https://www.nexaexperience.com/login.html?url=/buy-now.aspx",
		"Ignis": "https://www.nexaexperience.com/login.html?url=/buy-now.aspx",
		"Baleno RS": "https://www.nexaexperience.com/login.html?url=/buy-now.aspx",
		"OMNI": "https://www.marutisuzuki.com/corporate/reach-us/contact-us",
		"Gypsy": "https://www.marutisuzuki.com/corporate/reach-us/contact-us"	
    }
};
